name: Kiwi Changelogs

on:
  push:

jobs:
  notify:
    name: Kiwi Changelogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send commit message to Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: '${{ github.event.head_commit.message }}'
