name: Kiwi Changelogs

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        uses: appleboy/discord-action@v0.2.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            📄 **New commit** pushed to `${{ github.repository }}`  
            **Author:** ${{ github.actor }}  
            **Message:** ${{ github.event.head_commit.message }}  
            🔗 <${{ github.event.head_commit.url }}>
